version: '3.8'
services:
  user_service:
    build:
      context: '../user-service'
    container_name: dragonzo_user_service
    command: ['npm', 'run', 'start:debug']
    networks:
      dragonzo_net:
        aliases:
          - dragonzo_user_service
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    container_name: dragonzo_nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - default
      - dragonzo_net
networks:
  dragonzo_net: